name: lightweightRegression

on:
  pull_request:
    branches:
      - main

jobs:
  run-lightweight-regression:
    name: Run Lightweight Regression
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute script
        run: echo "Hello"
