name: Trigger Jenkins Manually

on:
    workflow_dispatch:
      inputs:
        pr_number:
          description: 'PR number to test'
          required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins
        run: |
          curl -X POST "https://public-endpoint/job/MY_JOB/buildWithParameters" \
            "auth_token:${{ secrets.JENKINS_TOKEN }}"
